### ISSUE TITLE
Changing textSize programmatically doesn't work

### ISSUE THREAD

**Issue by borjaruiz** [AndroidDeveloperLB/AutoFitTextView#16]
I'm trying to change the textSize programmatically according to the string length, but I don't see changes.

if(getItem( position ).getValue().length()<12){
			textView.setTextSize(18);
		}
		else{
			if(getItem( position ).getValue().length()>11&&getItem( position ).getValue().length()<25){
				textView.setTextSize(15);
			}
			else{
				textView.setTextSize(13);
			}
		}
		textView.setText( getItem( position ).getValue() );
		if(selectedItem==position){
			textView.setTypeface(selected);
			textView.setTextColor(context.getResources().getColor(R.color.white));
		}
		else{
			textView.setTypeface(unselected);
			textView.setTextColor(context.getResources().getColor(R.color.black));
		}

The typeface is being changed properly, but not the textSize (and there are a lot of different string sizes).

Thanks in advance.

**Comment by AndroidDeveloperLB** [comment]
The point of using this library is that it changes the font size
automatically, according to the dimensions restrictions imposed on it.
Please try out the sample of the library, to see how to use it.

**Comment by AndroidDeveloperLB** [comment]
Thank you for trying to help though.
