### ISSUE TITLE
Home widget

### ISSUE THREAD

**Issue by salvolf** [AndroidDeveloperLB/AutoFitTextView#17]
Hi,
I trie to add it in the home widget but I always get Problem loading widget and the widget does not get displayed.
Any ideas how to solve this problem?

**Comment by AndroidDeveloperLB** [comment]
If you mean AppWidget, you can't. In fact, you can't use customized views at all for AppWidgets.
They are very limited, about the same way as notifications.
For those, you can only use what's supported (only built in views), and even then, you are limited to just a few of them.

**Comment by salvolf** [comment]
Thanks for the quick reply.
;)

**Comment by AndroidDeveloperLB** [comment]
I'm not sure it's even possible to get the size of the widget, but maybe I'm wrong with this.
If you investigate it, please let me know what you've found.

**Comment by salvolf** [comment]
Yes, it's possible to implement resizing widget and get the size through the intent.
onReceive you can filter the intent action: android.appwidget.action.APPWIDGET_UPDATE_OPTIONS.
You can have the size in this way:

 Bundle widgetExtras = extras.getBundle(AppWidgetManager.EXTRA_APPWIDGET_OPTIONS);
widgetExtras.getInt(AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT))

**Comment by AndroidDeveloperLB** [comment]
Oh, I remember seeing this, but I never used it.
Maybe you can use it to your advantage, and try to put the correct size of the text font.

**Comment by salvolf** [comment]
Yea I could but i was looking for something cleaner :)

**Comment by AndroidDeveloperLB** [comment]
Well the code isn't much cleaner.
Then again, the official TextView is a lot larger and harder to understand (more than 8000 lines of code as I remember).
