### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by crysan** [AndroidDeveloperLB/AutoFitTextView#18]
Please create dependencies compile 'your.library'

**Comment by AndroidDeveloperLB** [comment]
I don't know how and I don't have the time. Sorry... :(

**Comment by crysan** [comment]
Ok ((

**Comment by AndroidDeveloperLB** [comment]
It's a single file, and I don't think it will change anytime soon.

**Comment by AndroidDeveloperLB** [comment]
Why close it? it's a good suggestion. I hope I will do it some day.

**Comment by crysan** [comment]
Okay. We are waiting. Thank U!
