### ISSUE TITLE
fit for Android 5.0+

### ISSUE THREAD

**Issue by THEONE10211024** [AndroidDeveloperLB/AutoFitTextView#19]
It seems that this TextView doesn't run well in Android 5.0+,How to fix it ?Thank you!

**Comment by AndroidDeveloperLB** [comment]
I think I know what you are talking about.
Are you talking about the blinking in the sample?
Yes the text does auto-fit. I wonder why it happens.

**Comment by AndroidDeveloperLB** [comment]
OK, I know why this happens.
Someone once suggested to add this code:
https://github.com/AndroidDeveloperLB/AutoFitTextView/pull/14

But in Lollipop, this seems to be a problem. Removing it will fix the blinking issue, but I wonder what will happen with what he wrote about.

**Comment by AndroidDeveloperLB** [comment]
Fixed, but still hope there is a solution for everyone. Can you please try it out?

**Comment by THEONE10211024** [comment]
OK ,I'll have a try!You did really a good job!

**Comment by AndroidDeveloperLB** [comment]
Sadly, I don't deserve the credits, as most of it is based on others' codes.
But thank you.
