### ISSUE TITLE
Data binding to an AutoResizeTextView causes the layout to crash

### ISSUE THREAD

**Issue by elmateo487** [AndroidDeveloperLB/AutoFitTextView#24]
On 5.1.1 with a note 5. When an AutoResizeTextView is bound through data binding, the layout crashes with an "IllegalArgumentException: Layout: -140 < 0". The textview is bound to an object with an empty value for the field.

This happens after onTestSize is called, AutoResizeTextView.java line 192 is called.

**Comment by AndroidDeveloperLB** [comment]
i never used binding. Have you tried without binding?

**Comment by elmateo487** [comment]
I think we found the issue. Will update when time allows. 

Testing out setting availableSpace.top bot right left to 0 if the value is less than 0

Same with mWidthLimit

**Comment by AndroidDeveloperLB** [comment]
If you know how to fix it, please put a pull request.
