### ISSUE TITLE
Truncated Word

### ISSUE THREAD

**Issue by mpekalski** [AndroidDeveloperLB/AutoFitTextView#25]
I have a layout that has two columns, they are defined as LinearLayout, see code below. I think AutoFixTextView does not take into account the size of the LinearLayout it is contained in, but one level up. This results in the word being truncated, see the attached screen-shot (it should end with PNG).

```
<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal"
    android:layout_gravity="center_vertical"
    android:background="@drawable/my_background_border"
    >
    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_gravity="center_vertical"
        android:background="@drawable/my_background_border"
        >
        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:orientation="vertical"
            android:layout_weight="1"
            android:gravity="center"
            android:background="@drawable/my_background_border"
            >
            <android.support.design.widget.FloatingActionButton
                android:id="@+id/previous_card"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical|left"
                android:src="@drawable/navigate_previous" />
            <android.support.design.widget.FloatingActionButton
                android:id="@+id/next_card"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical|left"
                android:src="@drawable/navigate_next" />

        </LinearLayout>
    </LinearLayout>

    <LinearLayout
        android:id="@+id/card_text_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:layout_gravity="center_vertical"
        android:background="@drawable/my_background_border"
        >
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:orientation="vertical"
            android:layout_weight="1"
            android:gravity="center"
            android:background="@drawable/my_background_border"
            >
            <com.thedatawise.www.toddlerflip.AutoResizeTextView
                android:id="@+id/card_back_text"
                android:textColor="#000"
                android:textAllCaps="true"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="center_vertical"
                android:textSize="100sp"
                android:text="BACK PAGE" />
        </LinearLayout>
    </LinearLayout>
</LinearLayout>
```

![capture _2016-03-05-22-18-38](https://cloud.githubusercontent.com/assets/2975068/13550540/81ecc838-e320-11e5-9d07-877b364cf4ad.png)

**Comment by AndroidDeveloperLB** [comment]
Please try to make a minimal example.
Also, I advice not to use so many LinearLayout. Especially when a part of it is the FAB.

**Comment by mpekalski** [comment]
I found the problem is related to using

```
android:textAllCaps="true"
```
in AutoResizeTextView. After I removed it everything works fine.

**Comment by AndroidDeveloperLB** [comment]
odd. didn't know this is causing issues. if you know how to fix it in the library, please show.

**Comment by mpekalski** [comment]
Check the PR #26, that is what worked for me.

**Comment by AndroidDeveloperLB** [comment]
I think you should also use this in the code:

http://developer.android.com/reference/android/widget/TextView.html#setAllCaps(boolean)

**Comment by mpekalski** [comment]
But it kind of does not make sense to use it. This whole workaround is there because setting setAllCaps property in XML does not work as expected, or rather it works after the text has been fitted to the TextView and this is what my code was intended to fix. So, why do you suggest me using setAllCaps?

**Comment by AndroidDeveloperLB** [comment]
I meant, if you use this solution, you should also override this method.
I agree that this is a weird situation. I was hoping you have a different
solution.
sorry.
Can you please make a minimal sample that shows the issue? Maybe I could
think of a solution.

**Comment by mpekalski** [comment]
Ok, I created a basic AndoridStudio project, and created a sample that has the same issue as the one described above. I commented out my fixes in AutoResizeTextView so if you compile it you will see the problem. The string I am trying to display is **HEllooooooooooWorld123**, and on the screen you cannot see **123**. Also the problem might be that I invoke the **setText()** in **OnCreate**, but I am not that familiar with Andorid development. Anyway, my fix worked. I will override setAllCaps to and submit another pull request.


[textviewproblem.zip](https://github.com/AndroidDeveloperLB/AutoFitTextView/files/160302/textviewproblem.zip)

**Comment by AndroidDeveloperLB** [comment]
ok, i think i've found the problem and how to fix it:
onTestSize function uses the normal text, and not after the transformation of textCaps.
What I need to add/change is:

            @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
            @Override
            public int onTestSize(final int suggestedSize, final RectF availableSPace) {
                _paint.setTextSize(suggestedSize);
                final TransformationMethod transformationMethod = getTransformationMethod();
                final String text;
                if (transformationMethod != null)
                    text = transformationMethod.getTransformation(getText(), AutoResizeTextView.this).toString();
                else text = getText().toString();
                ...

**Comment by AndroidDeveloperLB** [comment]
If you have time to add this as pull request, please do. If not, I will do it later. :)

**Comment by mpekalski** [comment]
Done, should be visible as the same pull request.

**Comment by AndroidDeveloperLB** [comment]
so i guess it's fixed.
