### ISSUE TITLE
Doesn't auto resize in the first time

### ISSUE THREAD

**Issue by hakan6000** [AndroidDeveloperLB/AutoFitTextView#28]
- I am trying to use AutoResizeTextView on a simple activity, but it fails on the first go. If the button is touched to auto resize there is no problem. But, the thing is, i need it to be resized when the activity is first created.
   - Here is the list of things i have tried: Created AutoRiseTextView in xml as a CustomView. Called "show_the_text" method twice on the start. Called the method twice with different texts. Moved container decleration to inside of onCreate. Used RelativeLayout insted of FrameLayout. Created a temporary TextView inside of FrameLayout with text in it.
   - I run the application on API23 emulator and API21 phone but result is the same.
   - I have to say that i am a begginer in programming. Any ideas are welcome.

![oncreateview](https://cloud.githubusercontent.com/assets/17483288/14287132/4cc3e464-fb5a-11e5-88da-c2a73186174d.png)

JAVA FILE

         public class MainActivity extends AppCompatActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            //auto resizing fails on the first run
            show_auto_resized_text();

            //but when we use user touch it works
            TextView button=(TextView) findViewById(R.id.text_button);
            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    show_auto_resized_text();
                }
            });
        }
        public void show_auto_resized_text(){
            FrameLayout text_container=(FrameLayout) findViewById(R.id.container);
            text_container.removeAllViews();
            int width= text_container.getWidth()-40;
            int height= text_container.getHeight()-40;
            AutoResizeTextView textView=new AutoResizeTextView(MainActivity.this);
            textView.setGravity(Gravity.CENTER_VERTICAL | Gravity.CENTER_HORIZONTAL);
            textView.setMaxLines(10);
            textView.setTextColor(Color.WHITE);
                    textView.setTextSize(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, height, getResources().getDisplayMetrics()));
            textView.setEllipsize(TextUtils.TruncateAt.END);
            textView.setLayoutParams(new ViewGroup.LayoutParams(width, height));
            final String DOUBLE_BYTE_SPACE = "\u3000";
            String fixString = "";
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.HONEYCOMB_MR1
            && android.os.Build.VERSION.SDK_INT <= android.os.Build.VERSION_CODES.ICE_CREAM_SANDWICH_MR1) {
                fixString = DOUBLE_BYTE_SPACE;
            }
            textView.setText(fixString + "THIS IS MY TEXT TO BE AUTO RESIZED" + fixString);
            text_container.addView(textView);
        }
    }

XML FILE

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingBottom="@dimen/activity_vertical_margin"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_vertical_margin"
        tools:context="com.kr.hakan.myapplication.MainActivity">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentTop="true"
            android:layout_above="@+id/text_button"
            android:background="#ff5b14"
            android:layout_margin="20dp"
            android:id="@+id/container"></FrameLayout>

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="Auto Resize The Text"
            android:id="@+id/text_button"
            android:layout_alignParentBottom="true"
            android:background="#000000"
            android:textSize="30sp"
            android:textColor="#ffffff"
            android:gravity="center" />
    </RelativeLayout>

**Comment by AndroidDeveloperLB** [comment]
I think this is the reason:
http://stackoverflow.com/q/10923321/878126
and solution:
http://stackoverflow.com/a/10923514/878126

You basically get the width&height of the container of the view that you create, before you give it a chance to know what size it should be. 
Instead of this, either use the function in the solution, or just put the AutoResizeTextView inside the XML file, and let it all be automatically for you.

The reason I wrote it in code was to demonstrate that it can adjust to various sizes.

**Comment by AndroidDeveloperLB** [comment]
In order to check that I'm correct, check the value that you get for :

int width=...

**Comment by CrandellWS** [comment]
maybe you can try to post a new delayed runnable to execute `show_auto_resized_text()` 

@hakan6000 you said you are learning so I am posting source here for your help but this may or may not help you for this issue...but sometimes allowing a delay does work for first run issues....(not the ideal fix but it can help in a pinch sometimes)


```
final Handler handler = new Handler();
handler.postDelayed(new Runnable() {
  @Override
  public void run() {
    //Do something after 100ms
  }
}, 100);
```

See -> http://stackoverflow.com/a/9166354/1815624

**Comment by AndroidDeveloperLB** [comment]
No, time handling isn't needed. plus there will be a time the use won't see it well.

**Comment by AndroidDeveloperLB** [comment]
Just use what I wrote there:

private static void runJustBeforeBeingDrawn(final View view, final Runnable runnable)
{
    final ViewTreeObserver vto = view.getViewTreeObserver();
    final OnPreDrawListener preDrawListener = new OnPreDrawListener()
    {
        @Override
        public boolean onPreDraw()
        {
            Log.d(App.APPLICATION_TAG, CLASS_TAG + "onpredraw");
            runnable.run();
            final ViewTreeObserver vto = view.getViewTreeObserver();
            vto.removeOnPreDrawListener(this);
            return true;
        }
    };
    vto.addOnPreDrawListener(preDrawListener);
}

alternatively , you can use addOnGlobalLayoutListener instead of addOnPreDrawListener if you wish.

**Comment by CrandellWS** [comment]
@hakan6000 AndroidDeveloperLB  is correct...

**Comment by hakan6000** [comment]
Thanks a lot **AndroidDeveloperLB**, it works now.

**Comment by AndroidDeveloperLB** [comment]
@hakan6000 You're welcomed. You are also invited to try my other repos. Recent one that I've made is a tool to convert your app's images into WebP:
https://github.com/AndroidDeveloperLB/WebpifyYourAndroidApp/
