### ISSUE TITLE
Add Edit Text for auto fitting

### ISSUE THREAD

**Issue by CrandellWS** [AndroidDeveloperLB/AutoFitTextView#29]
Repo -> 
- https://github.com/ViksaaSkool/AutoFitEditText
- my fork
  - https://github.com/CrandellWS/AutoFitEditText
  - set lib up to be used as a git submodule
    - https://github.com/CrandellWS/AutoFitEditTextLib

For a quick how to:

```
# add submodule to track master branch
git submodule add -b master [URL to Git repo];

# update your submodule
git submodule update --remote 
```

so it goes like this: 

```
git submodule add  https://github.com/CrandellWS/AutoFitEditTextLib 
git submodule update --remote 
```

See What you can do...But basically I need to use both libs because yours is  TextView and the other is EditText.

**Comment by CrandellWS** [comment]
@AndroidDeveloperLB I submitted this issue here and not the other repo because you are significantly more active on GitHub than the other libraries developer @ViksaaSkool

**Comment by AndroidDeveloperLB** [comment]
I don't understand what you show here.

**Comment by CrandellWS** [comment]
https://github.com/ViksaaSkool/AutoFitEditText is a library and app sample for Auto Resizing **EditText** 

This is the same as what your are doing with **TextView**

So I forked the Repos see a fork your repo and the other side by side:
https://github.com/CrandellWS/AutoFitTextView
https://github.com/CrandellWS/AutoFitEditText

Then just the libraries:
https://github.com/CrandellWS/AutoFitTextViewLib
https://github.com/CrandellWS/AutoFitEditTextLib

So now with the library repos you can easily add this library project to any Android Gradle setup using the method I discribed above:

```
git submodule add  https://github.com/CrandellWS/AutoFitEditTextLib 
git submodule update --remote 

```


@AndroidDeveloperLB (assuming you know how to use git from the command line ) try this:


git clone https://github.com/AndroidDeveloperLB/AutoFitTextView.git
cd AutoFitTextView
git submodule add  https://github.com/CrandellWS/AutoFitEditTextLib 
git submodule update --remote 

Then load that project to Android Studio and add the XML  as discribed at:
https://github.com/ViksaaSkool/AutoFitEditText/blob/master/README.md


and run it

**Comment by CrandellWS** [comment]
https://github.com/ViksaaSkool/AutoFitEditText is a library and app sample for Auto Resizing **EditText** 

This is the same as what your are doing with **TextView**

So I forked the Repos see a fork your repo and the other side by side:
https://github.com/CrandellWS/AutoFitTextView
https://github.com/CrandellWS/AutoFitEditText

Then just the libraries:
https://github.com/CrandellWS/AutoFitTextViewLib
https://github.com/CrandellWS/AutoFitEditTextLib

So now with the library repos you can easily add this library project to any Android Gradle setup using the method I discribed above:

```
git submodule add  https://github.com/CrandellWS/AutoFitEditTextLib 
git submodule update --remote 

```


@AndroidDeveloperLB (assuming you know how to use git from the command line ) try this:


```
git clone https://github.com/AndroidDeveloperLB/AutoFitTextView.git
cd AutoFitTextView
git submodule add  https://github.com/CrandellWS/AutoFitEditTextLib 
git submodule update --remote 
```

Then load that project to Android Studio and add the XML  as discribed at:
https://github.com/ViksaaSkool/AutoFitEditText/blob/master/README.md


and run it

**Comment by CrandellWS** [comment]
@AndroidDeveloperLB 
Github has some issues right now will come back to this later on...

https://status.github.com/

**Comment by AndroidDeveloperLB** [comment]
I suggest getting all that's the same for both EditText and TextView into a single class, and make both use it somehow.
