### ISSUE TITLE
Text not show in lollipop version 

### ISSUE THREAD

**Issue by Harin-Kaklotar** [AndroidDeveloperLB/AutoFitTextView#33]
Hi you made an amazing solution for the auto fit textview. It's really awesome. Today i am trying to apply this class on my sample project. It almost work perfectly on all android version except one version (it is **Lollipop** ).  **text is not display on the screen for the lollipop version**. I don't know why !!!
I check there is no mistake in my sample code.
Thanks for this superb class +1

**Comment by AndroidDeveloperLB** [comment]
My sample doesn't work on Lollipop?
As I remember, it worked fine.

**Comment by Harin-Kaklotar** [comment]
sorry @AndroidDeveloperLB, error in my code, Your code work perfectly  
Sorry again
and thanks for the quick solution :+1:
