### ISSUE TITLE
Size gets crazy inside a cardView in recyclerView

### ISSUE THREAD

**Issue by oskarko** [AndroidDeveloperLB/AutoFitTextView#35]
Hi!,

I've a recyclerView with a lot of cardView. Each cardView has an autoResizeTextView and when I scroll fastly (down & up) the autoResizeTextView gets crazy... too much little in the most of time.

How Can I resolve this?

thanks in advance!

**Comment by AndroidDeveloperLB** [comment]
It wasn't intended to use in this case and wasn't tested, but maybe try to disable the auto-resizing as long as the user scrolls?
Can you also show what you mean by "gets crazy" ?

**Comment by oskarko** [comment]
the text gets little. You scroll down & up repeatly and the text is smaller than ever!

**Comment by AndroidDeveloperLB** [comment]
@oskarko Could it be because of recycling of the view? 
Does each item in the RecyclerView provide the same amount of space for the view ?

**Comment by oskarko** [comment]
Simple add a listview with a lot of elements and scroll repeatly up & down. Look what happens ;)

**Comment by AndroidDeveloperLB** [comment]
Please make a sample. I might not be able to create the one you talk about.
Also, BTW, it is recommended to use RecyclerView.

**Comment by IonutNegru87** [comment]
I also encountered this issue. The size of the view get's smaller each time it get's redrawn. The weird thing is that it affects all other rows. It is like the size is synced between the rows.

**Comment by AndroidDeveloperLB** [comment]
Please make the smallest sample that shows the issue.

**Comment by AndroidDeveloperLB** [comment]
I've not being able to reproduce this issue. It works fine for me.
I've updated the sample to include one for RecyclerView (available via the menu).

**Comment by IonutNegru87** [comment]
I've notice that binarySearch() should return the `mid` value when `midValCmp == 0`, but the implementation of the size tester doesn't return `0`.
I think this is the main reason behind the text size always shrinking until the minimum allowed size.

**Comment by IonutNegru87** [comment]
I think one of the reasons for the size getting wrong values is because of programmatically setting the view properties.
For example I have something like this:
```
resizeView.setMaxLines(UserToken.isValid() ? 1 : 2);
resizeView.setLines(UserToken.isValid() ? 1 : 2);
// Set the size which should be used for the price content
// We use PX because the value obtained is already converted based on the display metrics
resizeView.setTextSize(TypedValue.COMPLEX_UNIT_PX, textSizeScaledPixels);
// Set the color (will be based on the current flow) for the price content
resizeView.setTextColor(textColor);
// Set the text
resizeView.setText(textValue);
```
This is called in `onBindViewHolder()` method of the adapter of the `RecyclerView`.

Could this affect the behaviour of the widget?

**Comment by AndroidDeveloperLB** [comment]
For some reason, when I clone the project to try this out, I get this error:

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Error:Execution failed for task ':AutoFitTextViewSample:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Information:Gradle tasks [:AutoFitTextViewSample:assembleDebug]
Information:BUILD FAILED

Any idea why it occurs? and how to fix it?

**Comment by AndroidDeveloperLB** [comment]
@IonutNegru87 I've tested the addition of the next lines to the sample I've created, and still can't see any issue:

                holder.textView.setMaxLines(position % 2 == 0 ? 1 : 2);
                holder.textView.setLines(position % 2 == 0 ? 1 : 2);
                holder.textView.setTextSize(TypedValue.COMPLEX_UNIT_DIP, 50);

Here:

[device-2016-09-27-102733.zip](https://github.com/AndroidDeveloperLB/AutoFitTextView/files/494809/device-2016-09-27-102733.zip)

**Comment by Reline** [comment]
In the sample, try changing the text view width from `match_parent` to `wrap_content` and I believe you will be able to reproduce this issue.

**Comment by onomated** [comment]
Anyone figure out this issue?  I'm encountering this as well whenever the textview is refreshed i.e. scrolled in from outside of the window bounds.  Occurs even outside recycler views.  I have a containing that can be moved to a drag and drop target.  Whenever the containing view is moved outside of the screen bounds and back in, the text gets smaller and smaller each time.

**Comment by IonutNegru87** [comment]
Android now supports resizing via [AutoSizing TextView](https://developer.android.com/preview/features/autosizing-textview.html).
You need to use Support Library 26.0 Beta and set an API level higher or equal to 14.
You can read more on their official documentation page.

**Comment by AndroidDeveloperLB** [comment]
@IonutNegru87 Indeed, but does it work well? I tried to use it but had building issues.
Not only that, but I noticed that even on their video demonstrating this feature, there is a very common issue of wrapping a single letter from one word to the next line:
https://youtu.be/1N9KveJ-FU8?t=799
Notice the "w" go to the next line, instead of staying inside the word "textview" and resizing the text size.

**Comment by AndroidDeveloperLB** [comment]
@IonutNegru87  I've just tested it, and it does indeed have this issue of weird wrapping of partial words.
I've reported about this here:
https://issuetracker.google.com/issues/38468964

**Comment by onomated** [comment]
Second @Reline's comment on this.  The issue is with adjusting dimensions by using `wrap_content`.  When `onSizeChanged` is invoked, the measured width and height are computed against new dimensions adjusted to the last text size adjustment as opposed to the original textview size on initial layout.  A quick workaround is to set explicit sizes (i.e. avoid `wrap_content` on the textview) or update `onSizeChanged` to capture the original size on first layout, similar to changes below.  These may have other implications, but so far so good with my testing.

```java
    private void adjustTextSize() {
        // This is a workaround for truncated text issue on ListView, as shown here: https://github.com/AndroidDeveloperLB/AutoFitTextView/pull/14
        // TODO think of a nicer, elegant solution.
//    post(new Runnable()
//    {
//    @Override
//    public void run()
//      {
        if (!_dimensionsSet)
            return;
        final int startSize = (int) mMinTextSize;
        final int heightLimit = _origHeight - getCompoundPaddingBottom() - getCompoundPaddingTop();
        _widthLimit = _origWidth - getCompoundPaddingLeft() - getCompoundPaddingRight();
        if (_widthLimit <= 0)
            return;
        _paint.set(getPaint());
        _availableSpaceRect.right = _widthLimit;
        _availableSpaceRect.bottom = heightLimit;
        superSetTextSize(startSize);
//      }
//    });
    }

@Override
    protected void onSizeChanged(final int width, final int height, final int oldwidth, final int oldheight) {
        super.onSizeChanged(width, height, oldwidth, oldheight);

        if (!_dimensionsSet) {
            _origWidth = width;
            _origHeight = height;
            _dimensionsSet = true;
        }

        if (width != oldwidth || height != oldheight)
            adjustTextSize();
    }
```
