### ISSUE TITLE
Setting maxlines and ellipsize doesn't ellipsize the end of the TextView

### ISSUE THREAD

**Issue by KaeMs** [AndroidDeveloperLB/AutoFitTextView#38]
I added 
        android:maxLines="5"
        android:ellipsize="end"

to put an ellipsis when the text reaches more than 5 lines, but it simply doesn't work or sometimes ellipsis is not in the right place (in the middle of the sentence)

**Comment by AndroidDeveloperLB** [comment]
Does it happen on the sample too?

**Comment by KaeMs** [comment]
Oh sorry I am mistaken, I used some other AutoResize and I got it mixed up, the error I posted is actually that AutoResizeTV's, yours actually worked but, when the content is actually 5 lines, it doesn't work. Somehow when user only writes 1 line, it gets enlarged and ellipsized.

As for your sample, I didn't try it there, I copied the code from your item.xml and use it in my ViewHolder..
