### ISSUE TITLE
AutoResizeTextView doesn't scale property if I set custom LetterSpacing

### ISSUE THREAD

**Issue by lukicmarko** [AndroidDeveloperLB/AutoFitTextView#42]
Since android support Letter Spacing from api 21, I needed to implement custom logic for that. I used [stackoverflow solution](http://stackoverflow.com/a/23216171). After applying  LetterSpacing text is too small. 
![screenshot_1484562939](https://cloud.githubusercontent.com/assets/6000858/21979610/ef907278-dbdf-11e6-8749-fa876eb3fc40.png)

**Comment by AndroidDeveloperLB** [comment]
ok

**Comment by lukicmarko** [comment]
@AndroidDeveloperLB may I create pull request add logic for LetterSpacing and resolve bug?

**Comment by AndroidDeveloperLB** [comment]
Sure. I still wait for another though:
https://github.com/AndroidDeveloperLB/AutoFitTextView/issues/37
I just hope they won't cause issues together.
